[target.x86_64-unknown-linux-gnu]
linker = "/home/alec/graalvm-ce-java11-21.0.0.2/languages/llvm/native/bin/clang"
ar = "/home/alec/graalvm-ce-java11-21.0.0.2/languages/llvm/native/bin/ar"
rustflags = [ "-C", "link-args=-lgraalvm-llvm", "-Og", "--emit=llvm-bc"]
